[package]
name = "tui_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-437 = "0.1.0"
glium = "0.35"
image = "0.25.2"
rand = "0.8.5"
rexpaint = "0.1.1"
